[package]
name = "src"
version = "1.1.0"
cairo-version = "2.2.0"

[tool.NodeGuardians]
part_3 = "Hello Guardian"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest